# Generated by Django 2.2.7 on 2019-12-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='addTime',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='updateTime',
            new_name='updated',
        ),
    ]
