# Generated by Django 3.0 on 2019-12-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_tweet_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='replay',
            field=models.BooleanField(default=False, verbose_name='Is a replay'),
        ),
    ]
