# Generated by Django 3.0 on 2020-02-04 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0009_remove_tweet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='disLiked',
            field=models.ManyToManyField(blank=True, related_name='disLiked', to=settings.AUTH_USER_MODEL),
        ),
    ]
