# Generated by Django 3.0 on 2020-02-04 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0010_tweet_disliked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='disLiked',
        ),
        migrations.AddField(
            model_name='tweet',
            name='disliked',
            field=models.ManyToManyField(blank=True, related_name='disliked', to=settings.AUTH_USER_MODEL),
        ),
    ]
