# Generated by Django 3.0 on 2020-02-04 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 4, 10, 4, 36, 102113), verbose_name='Date Joined'),
        ),
    ]
