# Generated by Django 3.0 on 2020-02-04 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200204_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 4, 10, 8, 24, 744775), verbose_name='Date Joined'),
        ),
    ]
