# Generated by Django 3.0 on 2020-02-05 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200204_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 11, 51, 18, 199455), verbose_name='Date Joined'),
        ),
    ]
