# Generated by Django 3.0 on 2020-02-05 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200205_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 12, 1, 13, 68314), verbose_name='Date Joined'),
        ),
    ]
