# Generated by Django 3.0 on 2019-12-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='users',
            new_name='user',
        ),
    ]
