# Generated by Django 3.0 on 2019-12-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191217_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
